# Generated by Django 4.2.7 on 2023-11-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('w_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viewpickupstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('AGENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecaster.agent')),
            ],
        ),
    ]
