# Generated by Django 4.2.7 on 2023-11-25 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecaster.product'),
        ),
    ]
