# Generated by Django 4.2.7 on 2023-11-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0004_alter_item_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Picup_Request',
        ),
        migrations.RenameModel(
            old_name='Work',
            new_name='Work_assign',
        ),
        migrations.RemoveField(
            model_name='item',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='viewpickupstatus',
            name='AGENT',
        ),
        migrations.DeleteModel(
            name='Wrequest',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='price',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Viewpickupstatus',
        ),
    ]
