# Generated by Django 4.2.7 on 2023-12-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0006_waste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='status',
        ),
    ]
