from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.login),
    path('logout', views.logout),
    path('companyhome', views.companyhome),
    path('manageagent',views.manageagent),
    path('addagent',views.addagent),
    path('viewpickuprequest',views.viewpickuprequest),
    path('feedback',views.feedback),
    path('assignworkcode',views.assignworkcode),
    path('assignwork/<int:id>',views.assignwork),
    path('viewpickupstatus',views.viewpickupstatus),
    path('viewcomplaintsendreply',views.viewcomplaintsendreply),
    path('sendreply/<int:id>',views.sendreply),
    path('managerecycleproduct',views.managerecycleproduct),
    path('addproduct',views.addproduct),
    path('verifyorder',views.verifyorder),
    path('viewitems',views.viewitems),
    path('agentlogin',views.agentlogin),
    path('agenthome',views.agenthome),
    path('viewassignedworkrequest',views.viewassignedworkrequest),
    path('updateworkstatus',views.updateworkstatus),
    path('update/<int:id>',views.update),
    path('trackrequest',views.trackrequest),
    path('updates',views.updates),
    path('logincode',views.logincode),
    path('addelement',views.addelement),
    path('additem',views.additem),
    path('editagent/<int:id>',views.editagent),
    path('deleteagent/<int:id>',views.deleteagent),
    path('edited',views.edited),
    path('editproduct/<int:id>',views.editproduct),
    path('deletep/<int:id>',views.deletep),
    path('editedp',views.editedp),

    path('sendd', views.sendd),
    path('publicwaste',views.publicwaste),
    path('search_viewassignedworkrequest',views.search_viewassignedworkrequest),
    path('search_viewpickuprequest',views.search_viewpickuprequest),
    path('search_viewpickupstatus',views.search_viewpickupstatus),
    path('search_feedback',views.search_feedback),
    path('search_viewcomplaintsendreply',views.search_viewcomplaintsendreply),
    path('search_verifyorder',views.search_verifyorder),
    path('search_trackrequest',views.search_trackrequest),
    path('search_updateworkstatus',views.search_updateworkstatus),
    path('search_manageagent',views.search_manageagent),
    path('search_managerecycleproduct',views.search_managerecycleproduct),
    path('accept/<int:id>',views.accept),
    path('reject/<int:id>',views.reject),

#android

    path('logincode1', views.logincode1),
    path('register',views.register),
    path('viewcmprply',views.viewcmprply),
    path('sendpickuprequest',views.sendpickuprequest),
    path('sendcomplaint',views.sendcomplaint),
    path('sendfeedback',views.sendfeedback),
    path('searchproduct',views.searchproduct),
    path('and_viewproduct',views.and_viewproduct),
    path('vieworderstatus', views.vieworderstatus),
    path('viewpayment', views.viewpayment),
    path('reportpublic', views.reportpublic),
    path('ordrprdctcard', views.ordrprdctcard),
    path('addtocart', views.addtocart),
    path('ordrprdctcodeand', views.ordrprdctcodeand),
    path('viewcart', views.viewcart),
    path('cancel_s_order', views.cancel_s_order),
    path('addtocartorder', views.addtocartorder),
    path('wasterequest',views.wasterequest),
    path('result',views.result),

]